# Generated by Django 5.1.3 on 2025-03-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryStudent',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('parent_contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('admission_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='student_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryStudent',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('parent_contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('admission_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='student_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorSecondaryStudent',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade', models.CharField(default='', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('parent_contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('admission_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='student_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='teachers/documents/')),
                ('is_class_master', models.BooleanField(default=False)),
                ('admission_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subjects', models.ManyToManyField(related_name='teachers', to='students.subject')),
            ],
        ),
    ]
