# Generated by Django 5.1.3 on 2025-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsetting',
            name='max_students',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
