# Generated by Django 5.1.3 on 2025-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_schoolsetting_max_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarystudent',
            name='grade',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='secondarystudent',
            name='grade',
            field=models.CharField(default='', max_length=10),
        ),
    ]
