# Generated by Django 5.1.3 on 2025-03-24 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_primarystudent_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='primarystudent',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='secondarystudent',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='seniorsecondarystudent',
            name='grade',
        ),
        migrations.AddField(
            model_name='primarystudent',
            name='grades',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='primary_students', to='students.class'),
        ),
        migrations.AddField(
            model_name='secondarystudent',
            name='grades',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_students', to='students.class'),
        ),
        migrations.AddField(
            model_name='seniorsecondarystudent',
            name='grades',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='senior_secondary_students', to='students.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='grades',
            field=models.ManyToManyField(related_name='teachers', to='students.class'),
        ),
    ]
