# Generated by Django 5.1.3 on 2025-03-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_class_remove_primarystudent_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarystudent',
            name='grades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_students', to='students.class'),
        ),
        migrations.AlterField(
            model_name='secondarystudent',
            name='grades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_students', to='students.class'),
        ),
        migrations.AlterField(
            model_name='seniorsecondarystudent',
            name='grades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senior_secondary_students', to='students.class'),
        ),
    ]
