# Generated by Django 5.1.3 on 2025-03-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_primarystudent_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarystudent',
            name='re_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seniorsecondarystudent',
            name='re_registered',
            field=models.BooleanField(default=False),
        ),
    ]
